### PR TITLE
Fix social links

### PR DESCRIPTION
**Pull request by championswimmer**
@shivamMg I have cherry-picked your commit https://github.com/OpenTechSummit/open-event-scraper/pull/15/commits/50ff00d464d5d7bf88e618eb9d18631b6a6d6e19 but used my own generator fix for empty icons (checks for both cases where url == "" and also where service type is not any one in the switch case)

@mariobehling 
I've also added `python event.py` to build.sh and run.sh so that `services.json` is regenerated every time.

### CODE REVIEW

**Comment by championswimmer** [comment]
@mariobehling 
You can check live version here 
http://championswimmer.in/2016.opentechsummit.net/programm/

**Comment by mariobehling** [comment]
@championswimmer not sure, why on your site there is a day May 6, but the script is working fine. So I merged it.

**Comment by mariobehling** [comment]
@championswimmer Please see my comment here https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/3#issuecomment-215134810

**Comment by shivamMg** [comment]
@mariobehling Here: https://github.com/OpenTechSummit/open-event-scraper/pull/19

**Pull request merged**
