### PR TITLE
Fix social links on navbar

### PR DESCRIPTION
**Pull request by shivamMg**
@mariobehling (Closed in favor of https://github.com/OpenTechSummit/open-event-scraper/pull/16)

First commit makes these changes persistent: https://github.com/OpenTechSummit/2016.opentechsummit.net/pull/29

Second commit are patches for (first and third)https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/3#issuecomment-214985798

### CODE REVIEW

**Comment by championswimmer** [comment]
@shivamMg can you make a PR for only this https://github.com/OpenTechSummit/open-event-scraper/pull/15/commits/50ff00d464d5d7bf88e618eb9d18631b6a6d6e19 

I made a better fix for https://github.com/OpenTechSummit/open-event-scraper/pull/15/commits/775dd68548104d54c8ac30ae602a8a73a993aca3 that covers point 2 as well. (i.e. removes blank spaces if there is a typo in the sheet) 

EDIT:
nvm, just did it here https://github.com/OpenTechSummit/open-event-scraper/pull/16

**Comment by shivamMg** [comment]
@championswimmer Alright, will reset it.

**Comment by championswimmer** [comment]
@shivamMg 
let it be, I made a PR which has both your and my commit :)

**Comment by championswimmer** [comment]
@shivamMg also, is it possible that the links do not go into the dropdown and are instead in line with the top of the dropdown, horizontally (like it is when screen is big) .

**Comment by shivamMg** [comment]
@championswimmer Yes it can be done, but not with default bootstrap elements. We will need to add custom css.

**Comment by championswimmer** [comment]
@shivamMg if we put it just outside the `navbar-collapse` div, but keep the `pull-right` class, it might work ?

**Comment by shivamMg** [comment]
@championswimmer Leave it, I'll work on it. I've created an issue [here](https://github.com/OpenTechSummit/open-event-scraper/issues/17), have some work now.

**Comment by championswimmer** [comment]
@shivamMg cool :+1:

**Pull request closed without merging**
